name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  MIX_ENV: test

jobs:
  static_code_analysis:
    name: Static Code Analysis
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        otp: ["26.2.1"]
        elixir: ["1.16.1", "1.17.3"]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: erlef/setup-beam@v1.18.2
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{ matrix.elixir }}

      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile

      - name: Check Code Format
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        otp: ["26.2.1"]
        elixir: ["1.16.1", "1.17.3"]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: erlef/setup-beam@v1.18.2
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{ matrix.elixir }}

      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile

      - name: Run test
        run: mix test --trace --slowest 10
